# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170614_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
